exclude:
  - README.md
  - AUTHORS
  - utils
  - LICENSE
permalink: pretty
markdown: kramdown

collections:
  events:
    output: true
    permalink: /events/:name/

sr:
  year: 2015 # which year of SR are we? (the year of the next competition)
  openings: false # are there open slots for accepting teams for this year?

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
