exclude:
  - README.md
  - AUTHORS
  - utils
  - LICENSE
  - Gemfile
  - Gemfile.lock
permalink: pretty
markdown: kramdown

collections:
  events:
    output: true
    permalink: /events/:name/

sr:
  year: 2015 # which year of SR are we? (the year of the next competition)
  openings: false # are there open slots for accepting teams for this year?
  branches:
    - Southampton
    - Bristol
    - Munich
    - London

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-lunr-js-search
